device = "GW5AST-138"


[regulator]
regulator_enable = false


[q0]
quad_clk_to_mac_sel = "CM0"
mac_quad_clk_sel = "Q0"
enable = false
pd_toggle_by_fabric = false
lane_reset_by_fabric = true
por_toggle_by_fabric = false
ref_pad0_freq = "0M"
ref_pad1_freq = "0M"
rx_eq_bias = 7
rx_quad_clk_internal_sel = "LN0_PMA_RX_CLK"
rx_quad_clk_sel = "Internal"
tx_quad_clk_internal_sel = "CM0"
tx_quad_clk_sel = "Internal"
ref_prop_dir = 1
refomux0_sel = 0
refimux0_sel = 0
refimux1_sel = 0
qpll0_ref_sel = 0
qpll1_ref_sel = 0
refmux_scheme = "USER_DEFINED"


[q1]
quad_clk_to_mac_sel = "CM0"
mac_quad_clk_sel = "Q0"
enable = false
pd_toggle_by_fabric = false
lane_reset_by_fabric = true
por_toggle_by_fabric = false
ref_pad0_freq = "0M"
ref_pad1_freq = "0M"
rx_eq_bias = 7
rx_quad_clk_internal_sel = "LN0_PMA_RX_CLK"
rx_quad_clk_sel = "Internal"
tx_quad_clk_internal_sel = "CM0"
tx_quad_clk_sel = "Internal"
ref_prop_dir = 1
refomux0_sel = 0
refimux0_sel = 0
refimux1_sel = 0
qpll0_ref_sel = 0
qpll1_ref_sel = 0
refmux_scheme = "USER_DEFINED"


[q0.ln0]
chbond_align_pattern1 = 124
chbond_align_pattern1_is_kcode = false
chbond_align_pattern2 = 124
chbond_align_pattern2_is_kcode = false
chbond_align_pattern3 = 124
chbond_align_pattern3_is_kcode = false
decode_mode = "OFF"
encode_mode = "OFF"
preamEn = false
rxBistInv = false
rxPattern = "PRBS31"
txBistInv = false
txPattern = "PRBS31"
cdr_gc_counter = 250
cdr_calib_clk_src = "AUTO"
chbond_enable = false
chbond_align_length = 0
chbond_align_pattern0 = 124
chbond_mst_sel = "q0.ln0"
chbond_max_skew = 8
ctc_enable = false
ctc_skipb_pattern = 28
ctc_skipb_pattern_is_kcode = false
ctc_clk_src = "fabric_c2i_clk"
ctc_mst_sel = "q0.ln0"
ctc_skipa_pattern = 28
ctc_rd_start_depth = "8"
enable = false
loopBack = "OFF"
pcs_rx_reset_by_fabric = true
pcs_tx_reset_by_fabric = true
pcs_tx_clk_src = 0
width_mode = 10
dr_rx_att = 7
dr_rx_att_boost = 0
rx_bit_invert = false
chbond_clk_src = "lane"
chbond_cfg_rd_start_depth = 8
dr_rx_boost = 9
rx_byte_invert = false
rx_coupling = "AC"
rx_data_manipulation_enable = false
eq_manual = false
rx_gear_rate = "1:1"
rx_if_cfg_rd_start_depth = 8
locked_from_fabric = false
rx_ovs_mode = "OFF"
rx_ovs_pll_src = "N/A"
rx_ovs_ratio = "N/A"
rx_pol_invert = false
rx_data_rate = "1.25G"
sr_sd_thsel = 3
rx_slip_distance = 8
idle_high_filter = 0
idle_low_filter = 0
chbond_trigger_by_fabric = true
ctc_skipb_pattern_enable = false
tx_bit_invert = false
tx_byte_invert = false
tx_data_manipulation_enable = false
txlev = 15
ffe_c1 = 0
ffe_cm = 0
ffe_manual = false
tx_gear_rate = "1:1"
tx_if_cfg_mst_sel = "q0.ln0"
tx_if_cfg_rd_start_depth = 8
tx_ovs_mode = "OFF"
tx_ovs_ratio = "N/A"
tx_pol_invert = false
tx_data_rate = "1.25G"
tx_slip_distance = 8
vddt = 900.0
word_align_enable = false
comma = "K28.5"
comma_mask = "1111111111"
ffe_c0 = 40
cpll_ref_sel = 0


[q0.ln1]
chbond_align_pattern1 = 124
chbond_align_pattern1_is_kcode = false
chbond_align_pattern2 = 124
chbond_align_pattern2_is_kcode = false
chbond_align_pattern3 = 124
chbond_align_pattern3_is_kcode = false
decode_mode = "OFF"
encode_mode = "OFF"
preamEn = false
rxBistInv = false
rxPattern = "PRBS31"
txBistInv = false
txPattern = "PRBS31"
cdr_gc_counter = 250
cdr_calib_clk_src = "AUTO"
chbond_enable = false
chbond_align_length = 0
chbond_align_pattern0 = 124
chbond_mst_sel = "q0.ln1"
chbond_max_skew = 8
ctc_enable = false
ctc_skipb_pattern = 28
ctc_skipb_pattern_is_kcode = false
ctc_clk_src = "fabric_c2i_clk"
ctc_mst_sel = "q0.ln1"
ctc_skipa_pattern = 28
ctc_rd_start_depth = "8"
enable = false
loopBack = "OFF"
pcs_rx_reset_by_fabric = true
pcs_tx_reset_by_fabric = true
pcs_tx_clk_src = 0
width_mode = 10
dr_rx_att = 7
dr_rx_att_boost = 0
rx_bit_invert = false
chbond_clk_src = "lane"
chbond_cfg_rd_start_depth = 8
dr_rx_boost = 9
rx_byte_invert = false
rx_coupling = "AC"
rx_data_manipulation_enable = false
eq_manual = false
rx_gear_rate = "1:1"
rx_if_cfg_rd_start_depth = 8
locked_from_fabric = false
rx_ovs_mode = "OFF"
rx_ovs_pll_src = "N/A"
rx_ovs_ratio = "N/A"
rx_pol_invert = false
rx_data_rate = "1.25G"
sr_sd_thsel = 3
rx_slip_distance = 8
idle_high_filter = 0
idle_low_filter = 0
chbond_trigger_by_fabric = true
ctc_skipb_pattern_enable = false
tx_bit_invert = false
tx_byte_invert = false
tx_data_manipulation_enable = false
txlev = 15
ffe_c1 = 0
ffe_cm = 0
ffe_manual = false
tx_gear_rate = "1:1"
tx_if_cfg_mst_sel = "q0.ln1"
tx_if_cfg_rd_start_depth = 8
tx_ovs_mode = "OFF"
tx_ovs_ratio = "N/A"
tx_pol_invert = false
tx_data_rate = "1.25G"
tx_slip_distance = 8
vddt = 900.0
word_align_enable = false
comma = "K28.5"
comma_mask = "1111111111"
ffe_c0 = 40
cpll_ref_sel = 0


[q0.ln2]
chbond_align_pattern1 = 124
chbond_align_pattern1_is_kcode = false
chbond_align_pattern2 = 124
chbond_align_pattern2_is_kcode = false
chbond_align_pattern3 = 124
chbond_align_pattern3_is_kcode = false
decode_mode = "OFF"
encode_mode = "OFF"
preamEn = false
rxBistInv = false
rxPattern = "PRBS31"
txBistInv = false
txPattern = "PRBS31"
cdr_gc_counter = 250
cdr_calib_clk_src = "AUTO"
chbond_enable = false
chbond_align_length = 0
chbond_align_pattern0 = 124
chbond_mst_sel = "q0.ln2"
chbond_max_skew = 8
ctc_enable = false
ctc_skipb_pattern = 28
ctc_skipb_pattern_is_kcode = false
ctc_clk_src = "fabric_c2i_clk"
ctc_mst_sel = "q0.ln2"
ctc_skipa_pattern = 28
ctc_rd_start_depth = "8"
enable = false
loopBack = "OFF"
pcs_rx_reset_by_fabric = true
pcs_tx_reset_by_fabric = true
pcs_tx_clk_src = 0
width_mode = 10
dr_rx_att = 7
dr_rx_att_boost = 0
rx_bit_invert = false
chbond_clk_src = "lane"
chbond_cfg_rd_start_depth = 8
dr_rx_boost = 9
rx_byte_invert = false
rx_coupling = "AC"
rx_data_manipulation_enable = false
eq_manual = false
rx_gear_rate = "1:1"
rx_if_cfg_rd_start_depth = 8
locked_from_fabric = false
rx_ovs_mode = "OFF"
rx_ovs_pll_src = "N/A"
rx_ovs_ratio = "N/A"
rx_pol_invert = false
rx_data_rate = "1.25G"
sr_sd_thsel = 3
rx_slip_distance = 8
idle_high_filter = 0
idle_low_filter = 0
chbond_trigger_by_fabric = true
ctc_skipb_pattern_enable = false
tx_bit_invert = false
tx_byte_invert = false
tx_data_manipulation_enable = false
txlev = 15
ffe_c1 = 0
ffe_cm = 0
ffe_manual = false
tx_gear_rate = "1:1"
tx_if_cfg_mst_sel = "q0.ln2"
tx_if_cfg_rd_start_depth = 8
tx_ovs_mode = "OFF"
tx_ovs_ratio = "N/A"
tx_pol_invert = false
tx_data_rate = "1.25G"
tx_slip_distance = 8
vddt = 900.0
word_align_enable = false
comma = "K28.5"
comma_mask = "1111111111"
ffe_c0 = 40
cpll_ref_sel = 0


[q0.ln3]
chbond_align_pattern1 = 124
chbond_align_pattern1_is_kcode = false
chbond_align_pattern2 = 124
chbond_align_pattern2_is_kcode = false
chbond_align_pattern3 = 124
chbond_align_pattern3_is_kcode = false
decode_mode = "OFF"
encode_mode = "OFF"
preamEn = false
rxBistInv = false
rxPattern = "PRBS31"
txBistInv = false
txPattern = "PRBS31"
cdr_gc_counter = 250
cdr_calib_clk_src = "AUTO"
chbond_enable = false
chbond_align_length = 0
chbond_align_pattern0 = 124
chbond_mst_sel = "q0.ln3"
chbond_max_skew = 8
ctc_enable = false
ctc_skipb_pattern = 28
ctc_skipb_pattern_is_kcode = false
ctc_clk_src = "fabric_c2i_clk"
ctc_mst_sel = "q0.ln3"
ctc_skipa_pattern = 28
ctc_rd_start_depth = "8"
enable = false
loopBack = "OFF"
pcs_rx_reset_by_fabric = true
pcs_tx_reset_by_fabric = true
pcs_tx_clk_src = 0
width_mode = 10
dr_rx_att = 7
dr_rx_att_boost = 0
rx_bit_invert = false
chbond_clk_src = "lane"
chbond_cfg_rd_start_depth = 8
dr_rx_boost = 9
rx_byte_invert = false
rx_coupling = "AC"
rx_data_manipulation_enable = false
eq_manual = false
rx_gear_rate = "1:1"
rx_if_cfg_rd_start_depth = 8
locked_from_fabric = false
rx_ovs_mode = "OFF"
rx_ovs_pll_src = "N/A"
rx_ovs_ratio = "N/A"
rx_pol_invert = false
rx_data_rate = "1.25G"
sr_sd_thsel = 3
rx_slip_distance = 8
idle_high_filter = 0
idle_low_filter = 0
chbond_trigger_by_fabric = true
ctc_skipb_pattern_enable = false
tx_bit_invert = false
tx_byte_invert = false
tx_data_manipulation_enable = false
txlev = 15
ffe_c1 = 0
ffe_cm = 0
ffe_manual = false
tx_gear_rate = "1:1"
tx_if_cfg_mst_sel = "q0.ln3"
tx_if_cfg_rd_start_depth = 8
tx_ovs_mode = "OFF"
tx_ovs_ratio = "N/A"
tx_pol_invert = false
tx_data_rate = "1.25G"
tx_slip_distance = 8
vddt = 900.0
word_align_enable = false
comma = "K28.5"
comma_mask = "1111111111"
ffe_c0 = 40
cpll_ref_sel = 0


[q1.ln0]
chbond_align_pattern1 = 124
chbond_align_pattern1_is_kcode = false
chbond_align_pattern2 = 124
chbond_align_pattern2_is_kcode = false
chbond_align_pattern3 = 124
chbond_align_pattern3_is_kcode = false
decode_mode = "OFF"
encode_mode = "OFF"
preamEn = false
rxBistInv = false
rxPattern = "PRBS31"
txBistInv = false
txPattern = "PRBS31"
cdr_gc_counter = 250
cdr_calib_clk_src = "AUTO"
chbond_enable = false
chbond_align_length = 0
chbond_align_pattern0 = 124
chbond_mst_sel = "q1.ln0"
chbond_max_skew = 8
ctc_enable = false
ctc_skipb_pattern = 28
ctc_skipb_pattern_is_kcode = false
ctc_clk_src = "fabric_c2i_clk"
ctc_mst_sel = "q1.ln0"
ctc_skipa_pattern = 28
ctc_rd_start_depth = "8"
enable = false
loopBack = "OFF"
pcs_rx_reset_by_fabric = true
pcs_tx_reset_by_fabric = true
pcs_tx_clk_src = 0
width_mode = 10
dr_rx_att = 7
dr_rx_att_boost = 0
rx_bit_invert = false
chbond_clk_src = "lane"
chbond_cfg_rd_start_depth = 8
dr_rx_boost = 9
rx_byte_invert = false
rx_coupling = "AC"
rx_data_manipulation_enable = false
eq_manual = false
rx_gear_rate = "1:1"
rx_if_cfg_rd_start_depth = 8
locked_from_fabric = false
rx_ovs_mode = "OFF"
rx_ovs_pll_src = "N/A"
rx_ovs_ratio = "N/A"
rx_pol_invert = false
rx_data_rate = "1.25G"
sr_sd_thsel = 3
rx_slip_distance = 8
idle_high_filter = 0
idle_low_filter = 0
chbond_trigger_by_fabric = true
ctc_skipb_pattern_enable = false
tx_bit_invert = false
tx_byte_invert = false
tx_data_manipulation_enable = false
txlev = 15
ffe_c1 = 0
ffe_cm = 0
ffe_manual = false
tx_gear_rate = "1:1"
tx_if_cfg_mst_sel = "q1.ln0"
tx_if_cfg_rd_start_depth = 8
tx_ovs_mode = "OFF"
tx_ovs_ratio = "N/A"
tx_pol_invert = false
tx_data_rate = "1.25G"
tx_slip_distance = 8
vddt = 900.0
word_align_enable = false
comma = "K28.5"
comma_mask = "1111111111"
ffe_c0 = 40
cpll_ref_sel = 0


[q1.ln1]
chbond_align_pattern1 = 124
chbond_align_pattern1_is_kcode = false
chbond_align_pattern2 = 124
chbond_align_pattern2_is_kcode = false
chbond_align_pattern3 = 124
chbond_align_pattern3_is_kcode = false
decode_mode = "OFF"
encode_mode = "OFF"
preamEn = false
rxBistInv = false
rxPattern = "PRBS31"
txBistInv = false
txPattern = "PRBS31"
cdr_gc_counter = 250
cdr_calib_clk_src = "AUTO"
chbond_enable = false
chbond_align_length = 0
chbond_align_pattern0 = 124
chbond_mst_sel = "q1.ln1"
chbond_max_skew = 8
ctc_enable = false
ctc_skipb_pattern = 28
ctc_skipb_pattern_is_kcode = false
ctc_clk_src = "fabric_c2i_clk"
ctc_mst_sel = "q1.ln1"
ctc_skipa_pattern = 28
ctc_rd_start_depth = "8"
enable = false
loopBack = "OFF"
pcs_rx_reset_by_fabric = true
pcs_tx_reset_by_fabric = true
pcs_tx_clk_src = 0
width_mode = 10
dr_rx_att = 7
dr_rx_att_boost = 0
rx_bit_invert = false
chbond_clk_src = "lane"
chbond_cfg_rd_start_depth = 8
dr_rx_boost = 9
rx_byte_invert = false
rx_coupling = "AC"
rx_data_manipulation_enable = false
eq_manual = false
rx_gear_rate = "1:1"
rx_if_cfg_rd_start_depth = 8
locked_from_fabric = false
rx_ovs_mode = "OFF"
rx_ovs_pll_src = "N/A"
rx_ovs_ratio = "N/A"
rx_pol_invert = false
rx_data_rate = "1.25G"
sr_sd_thsel = 3
rx_slip_distance = 8
idle_high_filter = 0
idle_low_filter = 0
chbond_trigger_by_fabric = true
ctc_skipb_pattern_enable = false
tx_bit_invert = false
tx_byte_invert = false
tx_data_manipulation_enable = false
txlev = 15
ffe_c1 = 0
ffe_cm = 0
ffe_manual = false
tx_gear_rate = "1:1"
tx_if_cfg_mst_sel = "q1.ln1"
tx_if_cfg_rd_start_depth = 8
tx_ovs_mode = "OFF"
tx_ovs_ratio = "N/A"
tx_pol_invert = false
tx_data_rate = "1.25G"
tx_slip_distance = 8
vddt = 900.0
word_align_enable = false
comma = "K28.5"
comma_mask = "1111111111"
ffe_c0 = 40
cpll_ref_sel = 0


[q1.ln2]
chbond_align_pattern1 = 124
chbond_align_pattern1_is_kcode = false
chbond_align_pattern2 = 124
chbond_align_pattern2_is_kcode = false
chbond_align_pattern3 = 124
chbond_align_pattern3_is_kcode = false
decode_mode = "OFF"
encode_mode = "OFF"
preamEn = false
rxBistInv = false
rxPattern = "PRBS31"
txBistInv = false
txPattern = "PRBS31"
cdr_gc_counter = 250
cdr_calib_clk_src = "AUTO"
chbond_enable = false
chbond_align_length = 0
chbond_align_pattern0 = 124
chbond_mst_sel = "q1.ln2"
chbond_max_skew = 8
ctc_enable = false
ctc_skipb_pattern = 28
ctc_skipb_pattern_is_kcode = false
ctc_clk_src = "fabric_c2i_clk"
ctc_mst_sel = "q1.ln2"
ctc_skipa_pattern = 28
ctc_rd_start_depth = "8"
enable = false
loopBack = "OFF"
pcs_rx_reset_by_fabric = true
pcs_tx_reset_by_fabric = true
pcs_tx_clk_src = 0
width_mode = 10
dr_rx_att = 7
dr_rx_att_boost = 0
rx_bit_invert = false
chbond_clk_src = "lane"
chbond_cfg_rd_start_depth = 8
dr_rx_boost = 9
rx_byte_invert = false
rx_coupling = "AC"
rx_data_manipulation_enable = false
eq_manual = false
rx_gear_rate = "1:1"
rx_if_cfg_rd_start_depth = 8
locked_from_fabric = false
rx_ovs_mode = "OFF"
rx_ovs_pll_src = "N/A"
rx_ovs_ratio = "N/A"
rx_pol_invert = false
rx_data_rate = "1.25G"
sr_sd_thsel = 3
rx_slip_distance = 8
idle_high_filter = 0
idle_low_filter = 0
chbond_trigger_by_fabric = true
ctc_skipb_pattern_enable = false
tx_bit_invert = false
tx_byte_invert = false
tx_data_manipulation_enable = false
txlev = 15
ffe_c1 = 0
ffe_cm = 0
ffe_manual = false
tx_gear_rate = "1:1"
tx_if_cfg_mst_sel = "q1.ln2"
tx_if_cfg_rd_start_depth = 8
tx_ovs_mode = "OFF"
tx_ovs_ratio = "N/A"
tx_pol_invert = false
tx_data_rate = "1.25G"
tx_slip_distance = 8
vddt = 900.0
word_align_enable = false
comma = "K28.5"
comma_mask = "1111111111"
ffe_c0 = 40
cpll_ref_sel = 0


[q1.ln3]
chbond_align_pattern1 = 124
chbond_align_pattern1_is_kcode = false
chbond_align_pattern2 = 124
chbond_align_pattern2_is_kcode = false
chbond_align_pattern3 = 124
chbond_align_pattern3_is_kcode = false
decode_mode = "OFF"
encode_mode = "OFF"
preamEn = false
rxBistInv = false
rxPattern = "PRBS31"
txBistInv = false
txPattern = "PRBS31"
cdr_gc_counter = 250
cdr_calib_clk_src = "AUTO"
chbond_enable = false
chbond_align_length = 0
chbond_align_pattern0 = 124
chbond_mst_sel = "q1.ln3"
chbond_max_skew = 8
ctc_enable = false
ctc_skipb_pattern = 28
ctc_skipb_pattern_is_kcode = false
ctc_clk_src = "fabric_c2i_clk"
ctc_mst_sel = "q1.ln3"
ctc_skipa_pattern = 28
ctc_rd_start_depth = "8"
enable = false
loopBack = "OFF"
pcs_rx_reset_by_fabric = true
pcs_tx_reset_by_fabric = true
pcs_tx_clk_src = 0
width_mode = 10
dr_rx_att = 7
dr_rx_att_boost = 0
rx_bit_invert = false
chbond_clk_src = "lane"
chbond_cfg_rd_start_depth = 8
dr_rx_boost = 9
rx_byte_invert = false
rx_coupling = "AC"
rx_data_manipulation_enable = false
eq_manual = false
rx_gear_rate = "1:1"
rx_if_cfg_rd_start_depth = 8
locked_from_fabric = false
rx_ovs_mode = "OFF"
rx_ovs_pll_src = "N/A"
rx_ovs_ratio = "N/A"
rx_pol_invert = false
rx_data_rate = "1.25G"
sr_sd_thsel = 3
rx_slip_distance = 8
idle_high_filter = 0
idle_low_filter = 0
chbond_trigger_by_fabric = true
ctc_skipb_pattern_enable = false
tx_bit_invert = false
tx_byte_invert = false
tx_data_manipulation_enable = false
txlev = 15
ffe_c1 = 0
ffe_cm = 0
ffe_manual = false
tx_gear_rate = "1:1"
tx_if_cfg_mst_sel = "q1.ln3"
tx_if_cfg_rd_start_depth = 8
tx_ovs_mode = "OFF"
tx_ovs_ratio = "N/A"
tx_pol_invert = false
tx_data_rate = "1.25G"
tx_slip_distance = 8
vddt = 900.0
word_align_enable = false
comma = "K28.5"
comma_mask = "1111111111"
ffe_c0 = 40
cpll_ref_sel = 0


